/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Unusual volume or volatility activity detection
 */
export interface UnusualActivityV1 {
  schema: "insights.unusual.v1";
  instrument_id: string;
  metric: "volume" | "volatility";
  window: "1h" | "24h";
  zscore: number;
  ts_ms: number;
}
