/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Large trade flow detection (lite version)
 */
export interface WhaleFlowsLiteV1 {
  schema: "insights.whales.lite.v1";
  instrument_id: string;
  venue_id: "polymarket" | "kalshi";
  impact: "LOW" | "MED" | "HIGH";
  direction: "buy" | "sell";
  post_move_bps: number;
  ts_ms: number;
}
