/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Normalized orderbook deltas with optional snapshots. Prices are implied probability in [0.0, 1.0].
 */
export interface NormalizedOrderBookDeltaV1 {
  schema: "md.orderbook.delta.v1";
  instrument_id: string;
  venue_id: "polymarket" | "kalshi";
  seq: number;
  ts_ms: number;
  /**
   * Array of [price, size] pairs where price is implied probability [0.0, 1.0]
   */
  bids: [number, number][];
  /**
   * Array of [price, size] pairs where price is implied probability [0.0, 1.0]
   */
  asks: [number, number][];
  is_snapshot: boolean;
}
