/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Series/collections discovery data from prediction market venues
 */
export interface RawSeriesDiscoveryV0 {
  envelope: {
    venue_id: "polymarket" | "kalshi";
    stream: "series_discovery";
    schema: "raw.series.v0";
    timestamp: string;
    metadata?: {
      discovery_timestamp?: string;
      discovery_page?: number;
    };
  };
  payload: {
    [k: string]: unknown;
  };
}
