/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Venue connector health monitoring
 */
export interface VenueHealthV1 {
  schema: "infra.venue_health.v1";
  venue_id: "polymarket" | "kalshi";
  status: "CONNECTED" | "DEGRADED" | "STALE";
  last_event_ts_ms: number;
  messages_per_second?: number;
  staleness_seconds?: number;
  observed_at_ms: number;
}
