/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Arbitrage opportunities between venues (lite version)
 */
export interface ArbitrageLiteV1 {
  schema: "insights.arb.lite.v1";
  instrument_id: string;
  long_venue: "polymarket" | "kalshi";
  short_venue: "polymarket" | "kalshi";
  edge_bps: number;
  depth_tier: "S" | "M" | "L";
  persistence_ms: number;
  last_seen_ms: number;
  fees_included: boolean;
}
