/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Price movers over time windows
 */
export interface MoversV1 {
  schema: "insights.movers.v1";
  instrument_id: string;
  window: "1h" | "24h";
  prob_now: number;
  prob_prev: number;
  delta_bps: number;
  imbalance_index: number;
  ts_ms: number;
}
