/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Normalized trade events with implied probability pricing
 */
export interface NormalizedTradeV1 {
  schema: "md.trade.v1";
  instrument_id: string;
  venue_id: "polymarket" | "kalshi";
  ts_ms: number;
  side: "buy" | "sell";
  prob: number;
  size: number;
  notional_usd?: number;
}
