/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Raw venue data envelope from connectors
 */
export interface RawEnvelopeV0 {
  schema: "raw.v0";
  venue_id: "polymarket" | "kalshi";
  stream: "orderbook" | "trades" | "status";
  instrument_native: string;
  partition_key: string;
  ts_event_ms: number;
  ts_ingest_ms: number;
  is_historical?: boolean;
  backfill_ts_ms?: number;
  payload: {
    [k: string]: unknown;
  };
}
