/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Category/tag discovery data for unified taxonomy from prediction market venues
 */
export interface RawCategoriesDiscoveryV0 {
  envelope: {
    venue_id: "polymarket" | "kalshi";
    stream: "category_discovery";
    schema: "raw.categories.v0";
    timestamp: string;
    metadata?: {
      discovery_timestamp?: string;
    };
  };
  payload: {
    [k: string]: unknown;
  };
}
