/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event discovery data from prediction market venues
 */
export interface RawEventsDiscoveryV0 {
  envelope: {
    venue_id: "polymarket" | "kalshi";
    stream: "event_discovery";
    schema: "raw.events.v0";
    timestamp: string;
    metadata?: {
      discovery_timestamp?: string;
      discovery_page?: number;
    };
  };
  payload:
    | EventDiscoveryPayloadV0
    | {
        [k: string]: unknown;
      };
}
/**
 * Structured payload for event discovery messages
 */
export interface EventDiscoveryPayloadV0 {
  event: EventMetadataV0;
  /**
   * Unique event identifier for this discovery message
   */
  event_id: string;
  /**
   * Type of discovery event
   */
  event_type: "discovered" | "updated" | "expired";
  /**
   * When this discovery event occurred
   */
  timestamp: string;
  /**
   * Venue identifier from venues.json registry
   */
  venue_id: "polymarket" | "kalshi";
  discovery_meta?: DiscoveryMetaV0;
}
/**
 * Structured metadata for individual prediction market events
 */
export interface EventMetadataV0 {
  /**
   * Discriminator field for event metadata
   */
  kind: "event";
  /**
   * Venue identifier from venues.json registry
   */
  venue_id: "polymarket" | "kalshi";
  /**
   * Venue-specific event identifier
   */
  event_id: string;
  /**
   * Event title
   */
  title: string;
  /**
   * Event description
   */
  description?: string;
  /**
   * Event category
   */
  category?: string;
  /**
   * Whether the event is currently active
   */
  active: boolean;
  /**
   * Whether the event is closed for trading
   */
  closed: boolean;
  /**
   * Event start date/time
   */
  start_date?: string;
  /**
   * Event end date/time
   */
  end_date?: string;
  /**
   * When this event was first discovered
   */
  discovered_at: string;
  /**
   * When this event was last seen in discovery
   */
  last_seen: string;
  /**
   * Series ID this event belongs to
   */
  parent_series_id?: string;
  /**
   * Series title for convenience
   */
  parent_series_title?: string;
  /**
   * Structured tags for categorization
   */
  tags?: string[];
  relationships?: RelationshipsV0;
  /**
   * Venue-specific fields that don't fit canonical schema
   */
  extra_metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Parent/child relationship mappings
 */
export interface RelationshipsV0 {
  /**
   * Parent series identifier
   */
  series_id?: string;
  /**
   * Child event identifiers
   */
  event_ids?: string[];
  /**
   * Related venue instrument identifiers
   */
  instrument_ids?: string[];
}
/**
 * Metadata about the discovery batch/run for monitoring and sequencing
 */
export interface DiscoveryMetaV0 {
  /**
   * Unique identifier for this discovery batch
   */
  batch_id: string;
  /**
   * Position of this item within the batch
   */
  batch_sequence: number;
  /**
   * Total number of items in this batch
   */
  batch_total_count: number;
  /**
   * Unique identifier for the entire discovery run
   */
  discovery_run_id: string;
}
