/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Series/collections discovery data from prediction market venues
 */
export interface RawSeriesDiscoveryV0 {
  envelope: {
    venue_id: "polymarket" | "kalshi";
    stream: "series_discovery";
    schema: "raw.series.v0";
    timestamp: string;
    metadata?: {
      discovery_timestamp?: string;
      discovery_page?: number;
    };
  };
  payload:
    | SeriesDiscoveryPayloadV0
    | {
        [k: string]: unknown;
      };
}
/**
 * Structured payload for series discovery messages
 */
export interface SeriesDiscoveryPayloadV0 {
  event: SeriesMetadataV0;
  /**
   * Unique event identifier for this discovery message
   */
  event_id: string;
  /**
   * Type of discovery event
   */
  event_type: "discovered" | "updated" | "expired";
  /**
   * When this discovery event occurred
   */
  timestamp: string;
  /**
   * Venue identifier from venues.json registry
   */
  venue_id: "polymarket" | "kalshi";
  discovery_meta?: DiscoveryMetaV0;
}
/**
 * Structured metadata for series/collections of prediction market events
 */
export interface SeriesMetadataV0 {
  /**
   * Discriminator field for series metadata
   */
  kind: "series";
  /**
   * Venue identifier from venues.json registry
   */
  venue_id: "polymarket" | "kalshi";
  /**
   * Series identifier (note: field name kept for compatibility)
   */
  event_id: string;
  /**
   * Series title
   */
  title: string;
  /**
   * Series description
   */
  description?: string;
  /**
   * Series category
   */
  category?: string;
  /**
   * Whether the series is currently active
   */
  active: boolean;
  /**
   * Whether the series is closed
   */
  closed: boolean;
  /**
   * When this series was first discovered
   */
  discovered_at: string;
  /**
   * When this series was last seen in discovery
   */
  last_seen: string;
  /**
   * Structured tags for categorization
   */
  tags?: string[];
  /**
   * Event IDs that belong to this series
   */
  child_event_ids?: string[];
  relationships?: RelationshipsV0;
  series_data?: SeriesDataV0;
  /**
   * Venue-specific fields that don't fit canonical schema
   */
  extra_metadata?: {
    [k: string]: unknown;
  };
}
/**
 * Parent/child relationship mappings
 */
export interface RelationshipsV0 {
  /**
   * Parent series identifier
   */
  series_id?: string;
  /**
   * Child event identifiers
   */
  event_ids?: string[];
  /**
   * Related venue instrument identifiers
   */
  instrument_ids?: string[];
}
/**
 * Series-specific fields
 */
export interface SeriesDataV0 {
  /**
   * Series ticker/symbol
   */
  ticker?: string;
  /**
   * URL-friendly series identifier
   */
  slug?: string;
  /**
   * Short series subtitle
   */
  subtitle?: string;
  /**
   * Type/classification of series
   */
  series_type?: string;
  /**
   * Series recurrence pattern
   */
  recurrence?: string;
  image_url?: string;
  icon_url?: string;
  /**
   * UI layout hint
   */
  layout?: string;
  financial?: FinancialDataV0;
  status?: StatusDataV0;
  contract?: ContractDataV0;
  timestamps?: TimestampDataV0;
  creators?: CreatorDataV0;
}
export interface FinancialDataV0 {
  /**
   * 24-hour USD volume, decimal precision to 2 places
   */
  volume_24h_usd?: number;
  /**
   * Total USD volume, decimal precision to 2 places
   */
  volume_total_usd?: number;
  /**
   * Total USD liquidity, decimal precision to 2 places
   */
  liquidity_total_usd?: number;
  /**
   * 24-hour contract volume count
   */
  volume_24h_contracts?: number;
  /**
   * Total contract volume count
   */
  volume_total_contracts?: number;
  /**
   * Ranking/scoring metric (unitless)
   */
  score?: number;
  /**
   * Currency unit for monetary values
   */
  currency?: "USD";
}
export interface StatusDataV0 {
  archived?: boolean;
  /**
   * Newly featured series
   */
  is_new?: boolean;
  featured?: boolean;
  /**
   * Access restrictions apply
   */
  restricted?: boolean;
  /**
   * Template for event generation
   */
  is_template?: boolean;
  /**
   * Competitive mode/flag
   */
  competitive?: string;
  comments_enabled?: boolean;
}
export interface ContractDataV0 {
  contract_url?: string;
  contract_terms_url?: string;
  /**
   * Fee calculation method
   */
  fee_type?: string;
  fee_multiplier?: number;
  additional_prohibitions?: string[];
  settlement_sources?: SettlementSourceV0[];
}
export interface SettlementSourceV0 {
  name: string;
  url?: string;
}
export interface TimestampDataV0 {
  published_at?: string;
  created_at?: string;
  updated_at?: string;
}
export interface CreatorDataV0 {
  created_by?: string;
  updated_by?: string;
}
/**
 * Metadata about the discovery batch/run for monitoring and sequencing
 */
export interface DiscoveryMetaV0 {
  /**
   * Unique identifier for this discovery batch
   */
  batch_id: string;
  /**
   * Position of this item within the batch
   */
  batch_sequence: number;
  /**
   * Total number of items in this batch
   */
  batch_total_count: number;
  /**
   * Unique identifier for the entire discovery run
   */
  discovery_run_id: string;
}
