name: Auto-Update Documentation

on:
  push:
    paths:
      - 'codegen/**'
      - 'schemas/**'
      - 'openapi/**'
      - 'scripts/generate-docs.mjs'
    branches: [ main ]

  # Allow manual triggering
  workflow_dispatch:

jobs:
  update-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate documentation
        run: npm run generate:docs

      - name: Check for documentation changes
        id: check_changes
        run: |
          if git diff --quiet docs/; then
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No documentation changes detected"
          else
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Documentation changes detected"
            git diff --name-only docs/
          fi

      - name: Commit documentation updates
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/
          git commit -m "📝 Auto-update documentation from codegen changes

          Generated from latest codegen artifacts to ensure documentation
          stays in sync with actual available types and functions.

          🤖 Auto-generated by GitHub Actions"

      - name: Push changes
        if: steps.check_changes.outputs.changes == 'true'
        run: git push

      - name: Comment on triggering commit
        if: steps.check_changes.outputs.changes == 'true' && github.event_name == 'push'
        uses: actions/github-script@v7
        with:
          script: |
            const commit = context.payload.head_commit;
            if (commit) {
              github.rest.repos.createCommitComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                commit_sha: commit.id,
                body: '📝 **Documentation Auto-Updated**\n\nThe documentation has been automatically updated to reflect the latest codegen changes.\n\n✅ Updated:\n- `docs/TYPESCRIPT_USAGE.md`\n- `docs/GO_MODULE_USAGE.md`\n\n*Generated by [Auto-Update Documentation workflow](https://github.com/' + context.repo.owner + '/' + context.repo.repo + '/actions)*'
              });
            }