name: Publish Go Module (go/ tag)

on:
  push:
    tags: ["go/v*.*.*"]

jobs:
  publish-go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Validate Go module
        run: |
          cd go
          go vet ./...
          go test ./...

      - name: Warm go proxy (optional)
        run: |
          VERSION=${GITHUB_REF_NAME#go/}
          MOD=github.com/sunday-xyz/schemas/go@${VERSION}
          echo "Warming proxy for: $MOD"
          curl -sSfL "https://proxy.golang.org/${MOD}/info" > /dev/null || true

      - name: Verify module availability
        run: |
          VERSION=${GITHUB_REF_NAME#go/}
          MOD=github.com/sunday-xyz/schemas/go@${VERSION}
          echo "Verifying module: $MOD"

          # Wait a bit for proxy to update
          sleep 10

          # Try to get the module info
          curl -sSfL "https://proxy.golang.org/${MOD}/info" || {
            echo "Module not yet available on proxy, this is normal"
            echo "It will be available once first requested by a user"
          }